### PR TITLE
include parent property alias in data element attribute

### PR DESCRIPTION
**Pull request by jezmaghuyop**
I've added the parent property alias as part of the value for data element attribute so that it can properly locate the DOM element, This is the fixed I've made for my project using Umbraco v7.15.3.

image

image

### CODE REVIEW

**Comment by skartknet** [comment]
Nice, thanks for that. Is this to fix the issue with nested content? Do you think it will work with v8 as well?

**Comment by jezmaghuyop** [comment]
@skartknet I've added a check now to identify if the property is in Nested Content or not.

**Comment by skartknet** [comment]
Great, I'll try to take a look this weekend and release a new version.

**Comment by skartknet** [comment]
I hit a case where it doesn't work:

image

In this line:
`var parentPropertyAlias = $scope.model.alias.toString().replace($scope.model.propertyAlias, '');`

the `$scope.model.alias` is cdnested__cd and the replace method remove the first 'cd', it should always remove whatever is after the '__'.

**Review by skartknet — APPROVED** [review]

**Pull request merged**
